### ISSUE TITLE
你好,大佬我在编译的时候出错了,能麻烦看一下嘛

### ISSUE THREAD

**Issue by shuyabin** [lx82319214/VirtualApp10#2]
![image](https://user-images.githubusercontent.com/14884581/85395237-68644880-b582-11ea-8a49-f459eb6c9ab6.png)

我的as版本是:3.5.3  ndk 版本是： 20.1.5948944

**Comment by sunnygql** [comment]
ndk 版本改为 16 的 就可以了

**Comment by shuyabin** [comment]
谢谢大佬。
